import{a as S,S as q,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const B="51048737-dc03a0e07e33d800e7c2950e1",P="https://pixabay.com/api/";async function f(o,r){const s={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r};try{return(await S.get(P,{params:s})).data}catch(a){throw console.error("Error fetching images:",a),a}}const h=document.querySelector(".gallery"),m=document.querySelector(".loader-backdrop"),g=document.querySelector(".load-more-btn"),R=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const r=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:t,views:l,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a href="${a}">
            <img src="${s}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <div class="info-block"><p class="label">Likes</p><p class="value">${t}</p></div>
            <div class="info-block"><p class="label">Views</p><p class="value">${l}</p></div>
            <div class="info-block"><p class="label">Comments</p><p class="value">${L}</p></div>
            <div class="info-block"><p class="label">Downloads</p><p class="value">${w}</p></div>
          </div>
        </li>
      `).join("");h.insertAdjacentHTML("beforeend",r),R.refresh()}function $(){h.innerHTML=""}function v(){m.style.display="flex"}function b(){m.style.display="none"}function E(){g.classList.remove("hidden")}function c(){g.classList.add("hidden")}const p=document.querySelector(".form"),M=document.querySelector(".load-more-btn");let d="",n=1,u=0;p.addEventListener("submit",async o=>{o.preventDefault();const r=p.elements["search-text"].value.trim();if(!r){i.warning({message:"Please enter a search query!",position:"topRight"});return}$(),c(),d=r,n=1,v();try{const s=await f(d,n);if(u=s.totalHits,s.hits.length===0){i.info({message:"No images found. Please try another search.",position:"topRight"});return}y(s.hits),E(),n*15>=u&&(c(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again.",position:"topRight"})}finally{b()}});M.addEventListener("click",async()=>{n+=1,v();try{const o=await f(d,n);y(o.hits),x(),n*15>=u&&(c(),i.info({message:"You've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Failed to load more images.",position:"topRight"})}finally{b()}});function x(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
